#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new App\Application();
require __DIR__.'/app/config/dev.php';
App\Application::config($app);

$console = require __DIR__.'/app/console.php';
$console->run();